include:
  # - board: nice_nano_v2
  #   shield: corne_left nice_view_adapter nice_view_gem
  #   artifact_name: corne_left
  # - board: nice_nano_v2
  #   shield: corne_right nice_view_adapter nice_view_gem
  #   artifact_name: corne_right
  - board: nice_nano_v2
    shield: chocorne_left
    artifact_name: chocorne_left
  - board: nice_nano_v2
    shield: chocorne_right
    artifact_name: chocorne_right
  - board: nice_nano_v2
    shield: settings_reset
